### ISSUE TITLE
Indexer property via interface implementation quick fix is invalid

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#233]
Implementing say `IDictionary<string, string>` via the interface implementation quick fix (very happy about it, many thanks @auduchinok) generates `member this.Item = failwith "todo"` however as it's an indexer it should actually be something like `member this.Item with get key = failwith "todo"`

**Comment by auduchinok** [comment]
@NinoFloris Thank you for reporting this! It has been implemented in [Rider 2022.2](https://github.com/JetBrains/resharper-fsharp/blob/net232/RELEASE_NOTES.md#20222).
