### ISSUE TITLE
sprintf to string interpolation refactor removes necessary parentheses

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#246]
For instance refactoring 

```fsharp
let value = "value"
invalidOp(sprintf "key has value '%s'" value)
```

becomes 

```fsharp
let value = "value"
invalidOp$"key has value '%s{value}'"
```

which fails to compile (though the editor does not show red squigglies until a build has happened, another bug?)

**Comment by auduchinok** [comment]
@NinoFloris Thanks!

@saul We should add a whitespace when removing parens (until the formatter does it for us).

**Comment by NinoFloris** [comment]
Could parentheses stick around for constructors and members? Functions is fine to simplify

**Comment by saul** [comment]
Raised PR to fix here: https://github.com/JetBrains/resharper-fsharp/pull/248
