### ISSUE TITLE
Suggested open for unknown attribute on module is placed inside the module

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#275]
Suggested open for unknown attribute on module is placed inside the module
```fs
namespace Test 

// Import missing reference
[<EditorBrowsable>]
module Code = 
   // It ends up here while it should be placed outside the module to bring the attribute in scope.

   let x = () 
```

**Comment by auduchinok** [comment]
And here's another set of improvements for previously not supported cases for top-level modules: [b827329](https://github.com/JetBrains/resharper-fsharp/commit/b827329bbfd84f5145b237c46db7f5879c8e1f2f), [5c0522a](https://github.com/JetBrains/resharper-fsharp/commit/5c0522a4e02420d0f6f167b5d3167ce8a96d5d5f).
