### ISSUE TITLE
inline function uses a private function is a compile error but IDE doesn't show it

### ISSUE THREAD

**Issue by DunetsNM** [JetBrains/resharper-fsharp#279]
Repro:

```
module InlineTest =
    let private innerFunc x = x + 1
    let inline inlineFunc x = (innerFunc x) + 1


[<EntryPoint>]
let main _argv =
    InlineTest.inlineFunc 7 |> ignore
    0
```

It expectedly gives a compilation error:

`Program.fs(3, 16): [FS1113] The value 'inlineFunc' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible`

But the IDE doesn't highlight the error (Rider 2021.1.3)

**Comment by DedSec256** [comment]
Thanks for the report! It looks like it's about FCS https://github.com/dotnet/fsharp/issues/11677
