### ISSUE TITLE
Still many colorization issues around moving string interpolations

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#282]
https://github.com/JetBrains/resharper-fsharp/issues/263#issuecomment-847639838

When changing a function body around a string interpolation there is still a lot of invalid colorization below an interpolated string. 2021.2 EAP 3

**Comment by NinoFloris** [comment]
This is also finally really fixed!

**Comment by NinoFloris** [comment]
Found another case, will try to repro

**Comment by NinoFloris** [comment]
```
module repro = 
    let x () =
        if not true then invalidOp $"Expected true but got {false}"
        0

    open System.Collections.Immutable

```

Indent 0 and deindent to see the open namespace discolor

**Comment by auduchinok** [comment]
Interesting, it seems either of https://github.com/JetBrains/resharper-fsharp/commit/76161eccf62a1bc09fa1070d351cac00dee0edce or https://github.com/JetBrains/resharper-fsharp/commit/b7cad4e8336810cc848e27e308de06bd379985fa has fixed this issue too. I cannot reproduce the indent/deindent 0 case anymore (though, it reproduces in the build without these changes).

**Comment by auduchinok** [comment]
OK, I've managed to reproduce now.

**Comment by auduchinok** [comment]
Here it goes: https://github.com/JetBrains/resharper-fsharp/commit/3e4f20ef0f9ca5c90c66f04e7e82405dea1123d0. @NinoFloris Thanks for all the repro cases, it helped to find the root cause!
