### ISSUE TITLE
Go to definition on ICollection<'T> shows me ICollection

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#283]
Go to definition on ICollection<'T> (but also all the other generic/nongeneric types) shows me ICollection, once ICollection is visited once. This looks like a cache lookup issue not taking into account generic parameters.

```fs
open System.Collections
let x: Generic.ICollection<int> = null 
let y: ICollection = null 
```

Repro:
1. Go to `Generic.ICollection<'T>` on x, everything fine.
2. Go to `ICollection` on y, also fine.
2.  Go to `Generic.ICollection<'T>` on x again, end up on `ICollection`.

**Comment by DedSec256** [comment]
Not reproduced in Rider 2022.2.

Can you re-check, please?

**Comment by auduchinok** [comment]
I also cannot reproduce it. @NinoFloris If you happen to see this again, please let us know.
