### ISSUE TITLE
Perf regression in 2021.2 EAP4?

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#284]
Many actions like (un)indent have become very slow, as if any action now blocks the reactor until a typecheck is finished. Did something heavy get switched on by default that wasn't before or is this an fcs regression?

It's easiest to experience this in a largeish solution where you try to indent multiple times in succession, the first time it's usually ok but it completely blocks for later attempts.

**Comment by auduchinok** [comment]
@NinoFloris Could you share any performance profile, please? It's Help -> Diagnostic tools -> Profile backend with sampling.

> Many actions like (un)indent have become very slow, as if any action now blocks the reactor until a typecheck is finished.

The reactor was removed in FCS, and that change got into EAP 4. I think it's the most impactful change in the plugin, but there're chances it could also be something in the rest of the product. Without looking at profiling data, it's difficult to think about it further, though.

Could I also ask to to create a YouTrack issue, so the regression is tracked by the rest of the team?

**Comment by NinoFloris** [comment]
:/ https://youtrack.jetbrains.com/issue/DEXP-603040

**Comment by NinoFloris** [comment]
Issue on perf regression is here https://youtrack.jetbrains.com/issue/RIDER-64619

**Comment by NinoFloris** [comment]
Things are fast in EAP 6!

**Comment by auduchinok** [comment]
@NinoFloris Great, thanks for the update!

There was another FCS bump with reanalysis (and performance) fixes in EAP 6.

**Comment by NinoFloris** [comment]
I actually meant this issue in https://github.com/JetBrains/resharper-fsharp/issues/291#issuecomment-878589185

**Comment by auduchinok** [comment]
@NinoFloris Oh, I see, thanks.

**Comment by auduchinok** [comment]
@NinoFloris Can you confirm the build provided in [RIDER-65187](https://youtrack.jetbrains.com/issue/RIDER-65187) fixes it?

**Comment by NinoFloris** [comment]
I think so, I haven't had the issue anymore but I must say I haven't done as much dev on that project the last days as previously. I think it's good to go for EAP 7 regardless :)

**Comment by NinoFloris** [comment]
I haven't had any slowdowns that wouldn't resolve anymore (certainly the F# compiler still takes its time now and then after changes) so I'll close the issue. I'll open a new one if I find something else!

**Comment by auduchinok** [comment]
@NinoFloris Thanks for the follow up!
