### ISSUE TITLE
Intra assembly types often don't update 

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#291]
Working with EAP 6 I'm noticing quite a bit of staleness. Inter-assembly I'm used to and is almost always fixed with an explicit build. In this case however it's often intra-assembly. Where changing/adding/removing a type in a different file doesn't flow to other files, not even after an explicit build. The one thing that seems to help is to cause a change in another project * and then build * which I assume causes a full recheck of all projects.

I might be able to create a repro but it doesn't seem to be entirely consistent.

**Comment by auduchinok** [comment]
@NinoFloris Thanks, I've already been looking into it today.

**Comment by auduchinok** [comment]
A workaround is to do a Unload/Reload project in Solution tree for now.

**Comment by NinoFloris** [comment]
Hey, I just got into a slow state again, what's the best way to give you the dump?

**Comment by auduchinok** [comment]
@NinoFloris Thanks, I'm able to reproduce it on my side. It's more interesting how we get into this state than looking at the state itself.

**Comment by auduchinok** [comment]
I've lost one of the file system shim calls during one of FCS updates, and it was hidden by other reanalysis issues in FCS. The FCS issues have seemingly been fixed (I couldn't repro it at least, and F# team is now aware of any remaining repro cases), and I've fixed the shim call in https://github.com/JetBrains/resharper-fsharp/commit/0a6180ebb4eeaa264e022b80872898d1f3ed8ab4.

**Comment by NinoFloris** [comment]
Thanks for this one!
