### ISSUE TITLE
Newest SDK not available for F# interactive

### ISSUE THREAD

**Issue by Tarmil** [JetBrains/resharper-fsharp#303]
The most recent SDK listed is 5.0.100, even though I have 5.0.400 and 6.0.100-preview.7 installed.

![image](https://user-images.githubusercontent.com/921395/129578587-2ca29881-cc92-458b-a78f-6d05825624ce.png)

I wonder if this is related to the fact that in these more recent SDKs, the fsi file is now called `fsi.dll` rather than `fsi.exe` in older SDKs?

OS: Windows 10
Rider version: 2021.2

**Comment by auduchinok** [comment]
That's interesting. I have 5.0.400 installed, and it shows up correctly:
<img width="738" alt="Screenshot 2021-08-16 at 19 08 17" src="https://user-images.githubusercontent.com/3923587/129594570-dc98191c-f885-49a6-b8d9-591358696af0.png">

Maybe it's something to do with .NET 6 preview, I'll need to take a look.

**Comment by auduchinok** [comment]
And the same after installing the preview:
<img width="730" alt="Screenshot 2021-08-16 at 19 13 40" src="https://user-images.githubusercontent.com/3923587/129595455-61a2821c-02b6-4f0f-8a73-efe8e929e5dc.png">

Does enabling the "Choose F# Interactive automatically" checkbox change anything for you?

**Comment by Tarmil** [comment]
Oh, I'm on another machine right now so I can't say for sure, but I think this was just because I had a global.json in that project.

**Comment by auduchinok** [comment]
@Tarmil Does it still reproduce for you?

**Comment by Tarmil** [comment]
Now on Rider 2021.3, it lists and chooses the expected .NET SDK 6.0.100. I think this can be closed.
