### ISSUE TITLE
Erroneous remove parens hint

### ISSUE THREAD

**Issue by bartelink** [JetBrains/resharper-fsharp#333]
Using Rider 2021.3.2 on Mac x64, I followed two hints to remove parens (on active patterns) without paying attention, and it broke my build.

The second one is [obviously] correct, but the first one changed the meaning - the build is fixed when I undo both:

https://github.com/jet/dotnet-templates/pull/112/commits/bf07b2666c7854dc7ea6d50bd9676585fef0d128

The second removal is fine when applied on its own:

https://github.com/jet/dotnet-templates/pull/112/commits/a89537bc5022322826439dccf96694e30704e477

When the suggestion is applied, the function signature as surfaced by Rider changes from:

![image](https://user-images.githubusercontent.com/206668/149569326-f79628ea-378a-4ed9-8723-2c542640bb1d.png)

to

![image](https://user-images.githubusercontent.com/206668/149569408-d5c70a05-af63-4999-82e2-c787402276c3.png)

when the change is applied.

Producing a more minimal repro may not be trivial - a key contributing factor may be the fact that the codebase is an uber-messy `dotnet new` template, and I need to manually flip the ifdef on L19 in that file for Rider to show the code. In other words, I imagine its possible that the logic may be working based on best effort heuristics, so I'm comfortable with closing this unless it's symptomatic of an obvious thing that can also arise in normal code. (I'll be on alert for simpler repros for as long as this remains open)

**Comment by auduchinok** [comment]
@bartelink Thanks for reporting it! It's just been fixed in [b0c91a4](https://github.com/JetBrains/resharper-fsharp/commit/b0c91a4dba6e967d126997344fa846f6263c6f6d).

**Comment by bartelink** [comment]
Wonderful, thanks for the speedy work!
