### ISSUE TITLE
Missing constraint info in language model

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#337]
I have one other F# -> C# IDE issue concerning type parameter constraints. These seem to be missing in the F# type info resharper consults from C# projects.

I have added the repro on top of the previous commit in the https://github.com/NinoFloris/IVT-rider-repro 

https://github.com/NinoFloris/IVT-rider-repro/commit/d4cfe7f754e77b47cefd0e49400ba2360635b815

Beyond IDE errors it also means Rider is failing to scaffold the interface stubs in C# for F# interfaces that will actually compile as the constraints are missing when it generates these.

**Comment by auduchinok** [comment]
@NinoFloris Thanks! Fixed in [5721f14](https://github.com/JetBrains/resharper-fsharp/commit/5721f14d2e3c0482b09dbbfaf0b3ca250752e50f) and [b63f18f](https://github.com/JetBrains/resharper-fsharp/commit/b63f18f1d1a28460021e2ab6e476405c34710522).
