### ISSUE TITLE
Actions on Save Fantomas Format doesn't work

### ISSUE THREAD

**Issue by xankz** [JetBrains/resharper-fsharp#351]
Enabling "Reformat and Cleanup Code" in Rider's Actions on Save does not automatically call Fantomas on save. It works when I do it manually from the menu though.

Looking further, I don't see any F# tasks in Editor > Code Cleanup at all

**Comment by DedSec256** [comment]
Thanks for the issue, I'll take a look at it!

**Comment by DedSec256** [comment]
@kinesivan, may I know your Rider version? Are there any errors in the code? Is it a script file or a simple .fs file in a project? It would be really nice if you could attach the code snippet since I can't reproduce the issue in Rider 2021.3.3 and Rider 2022.1 EAP.
