### ISSUE TITLE
Breakpoints improperly getting hit on file with same name

### ISSUE THREAD

**Issue by NatElkins** [JetBrains/resharper-fsharp#43]
I have multiple projects with files called Utils.fs.  When I set a breakpoint in one, both get hit.  See attached screenshot.  Notice that only the text in the background (where the breakpoint is getting hit) does not match the debugger modal.

Both are line 23, both are Utils.fs.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1795462/55567904-a7338780-56cc-11e9-8d35-ddfc354d17a4.png">

**Comment by auduchinok** [comment]
@NatElkins Sorry for the long response. Is there a chance you could check if it reproduces in recent builds, e.g in 2019.3 EAP?

@Iliya-usov have you seen something like this before?

**Comment by auduchinok** [comment]
Closing the stale issue. @NatElkins If you happen to see this again, please let us know.
