### ISSUE TITLE
Possible to write a custom plugin that uses FSharp.Compiler.Service from this plugin?

### ISSUE THREAD

**Issue by cmeeren** [JetBrains/resharper-fsharp#461]
I'm experimenting with creating a new F# linter. I'd like to integrate it into Rider using a plugin. (I currently have no idea how to do that, but that's another matter. Any tips are welcome!)

Is it possible, and would it be a good idea, to use FSharp.Compiler.Service through resharper-fsharp?

My thinking is that if I write a completely separate plugin that uses FSharp.Compiler.Service, I imagine the performance would be quite a bit worse than if I simply use the analysis results that resharper-fsharp already has.

**Comment by MangelMaxime** [comment]
I think Fantomas is using its own instance of FSharp.Compiler.Service without too much impact on the performance.

I take also this opportunity to share my thought on your linter tightly couple with Rider:

- CI will not be able to invoke it so no way to automate linter checking to refuse PR with invalid code
- Only Rider users will be able to use it not people from VS, VSCode, Vim, etc. so the linter is not really a linter for the F# ecosystem

**Comment by cmeeren** [comment]
> I think Fantomas is using its own instance of FSharp.Compiler.Service without too much impact on the performance.

Yes, but Fantomas is using the untyped AST only, right? The linter would, for some rules (e.g. like "always use `use` with `IDisposable`"), need to use the typed AST, which AFAIK is a lot slower. I was thinking that if I could use already type-checked results, that would improve performance quite a bit.

> I take also this opportunity to share my thought on your linter tightly couple with Rider:
> 
> * CI will not be able to invoke it so no way to automate linter checking to refuse PR with invalid code
> * Only Rider users will be able to use it not people from VS, VSCode, Vim, etc. so the linter is not really a linter for the F# ecosystem

To be clear, I do not intend to tightly integrate with Rider only. The "core" part of the linter would probably be a dotnet tool, and any IDE integration (and usage of already existing ASTs from those IDEs) would be added on top. Though I can easily imagine that being a bit troublesome, since IDEs would use different versions of FSharp.Compiler.Service.

Right now, I am experimenting with using FSharp.Analyzers.SDK. I have raised [an issue here](https://github.com/ionide/FSharp.Analyzers.SDK/issues/44) about AST traversal. Perhaps you have some input?

**Comment by MangelMaxime** [comment]
Another example is Fable, Fable use the F# AST and outside of the initial compilation time which takes some times because the F# compiler needs to initialise itself, the first version of the files, subsequent compilation from Fable are really fast.

So running several FCS instances is not problem IHMO and would avoid you having to support different version of FCS which always seems to be problematic because it often has breaking changes between releases.

**Comment by cmeeren** [comment]
Thanks, makes sense.
