### ISSUE TITLE
Provide documentation on how to dump PSI to a file

### ISSUE THREAD

**Issue by dawedawe** [JetBrains/resharper-fsharp#487]
Hey,
I just learned from a more experienced colleague how to use the `FSharpParserTest._` test to dump the PSI of `_.fs` to a file.
This was quite helpful to make a bit of progress in an issue I'm working on.

Would you be interested in adding documentation for that? If so, I'd be happy to do a PR for this.

**Comment by auduchinok** [comment]
Hi @dawedawe,

Yes, by all means open a PR with additional documentation. It would be nice to cover things that you found useful to know.

**Comment by auduchinok** [comment]
Speaking about dumping a PSI tree, it would be nice to add an internal action to dump a tree, similar to [these](https://github.com/JetBrains/resharper-fsharp/blob/e93f1b8c33af7200ffbb017c6559b329fa5c79a4/ReSharper.FSharp/src/FSharp.Psi.Features/src/Internal/FSharpInternalActionGroup.fs). It would call the same helper as `ParserTestBase` to get the textual representation and it would make checking the tree structure even easier. Is it something that you could also be interested in doing?

if you have any questions about the plugin, please write me on Slack anytime too

**Comment by dawedawe** [comment]
Sounds great, thanks. I'll try to come up with something.
Where on slack can I find you?

**Comment by auduchinok** [comment]
I'm @auduchinok on F# Slack

**Comment by dawedawe** [comment]
Oh well, I'm still waiting for my access there :(
Meanwhile, I messaged you on Discord, hope that's okay.

**Comment by auduchinok** [comment]
The action has been added.
