### ISSUE TITLE
Use the official version of the compiler service instead of a fork.

### ISSUE THREAD

**Issue by safesparrow** [JetBrains/resharper-fsharp#497]
Hi,

I would love if the plugin used the official version of the compiler without the need for custom code changes to be applied.

I know this was previously discussed and there are some obstacles.

Nonetheless I would like to report that achieving that would make it easier for people to contribute to the plugin and test FCS changes against Rider even before they are merged to master, without dealing with lots of merge conflicts or similar issues. This would benefit Rider in the long term.

Related issue, also in the "Makes contributions easier" space: https://github.com/JetBrains/resharper-fsharp/issues/494

**Comment by auduchinok** [comment]
We've discussed it with @safesparrow and @nojaf, and I'm going to close this issue. We're not going to migrate from the fork, as it'll bring too many technical issues to fix along the way. The best thing would be to try to update our fork more often and to make it easier to use a self-built FCS, to make it easier to test local FCS changes in the plugin.
