### ISSUE TITLE
Question: how does FSharpImportTypeHelper operate?

### ISSUE THREAD

**Issue by En3Tho** [JetBrains/resharper-fsharp#510]
```fsharp
[<Language(typeof<FSharpLanguage>)>]
type FSharpImportTypeHelper() =
    let [<Literal>] opName = "FSharpImportTypeHelper.FindTypeCandidates"

    let isApplicable (context: IFSharpReferenceOwner) =
        let referenceName = context.As<ITypeReferenceName>()
        isNull (OpenStatementNavigator.GetByReferenceName(referenceName))

    interface IImportTypeHelper with
        member x.FindTypeCandidates(reference, importTypeCacheFactory) =
            ... // what exact type candidates should this return?
```

I'm trying to poke around this thing to introduce an Extension-method import helper.
The only working case I managed to run is  something like this:
```fsharp
module SuperExt =    
    [<AbstractClass; Sealed; Extension>]
    type Int32Extensions() =
        [<Extension>]
        static member ModuleExtension(this: Int32) = ()

open SuperExt // import results in this open statement

module Test1 =    
    let testModuleExtension() =
        let x = 1
        x.ModuleExtension() // call import here
```
E.g. when this is a Extension class inside a module w/o namespaces in path.
I'm curious what types this import helper is expexted to return?

Case that I haven't managed to run properly for example:

```fsharp
module SuperExt =
    
    type Int32 with
        member _.Module() = ()

module Test1 =
    let testModule() =
        let x = 1
        x.Module() // I'm able to find SuperExt module but nothing happens
```

Also, I'm not sure why, but I can't seem to return full clr names and only simple class names. I guess I'm doing something wrong because this results in potentially wrong imports when Extension classes have the same name

**Comment by auduchinok** [comment]
> Question: how does FSharpImportTypeHelper operate?

It traverses the symbol cache (the scope created in `FSharpImportTypeFix`) and gets types that match the name of the reference. It then checks if each of the type can be accessed from this location and returns the applicable types to the platform.

The search for extension methods would be different, as the relevant ReSharper caches are different, and so are import helpers and the quick fix base classes. F# adds an additional complexity here, as there are also non-C#-compatible extensions that aren't currently analysed by ReSharper. For this to work properly, we need to find a way to search for F# extensions (including properties!) in the platform code that is currently only expects C#-style extension methods. This may require changes in ReSharper itself and/or some changes in caches for F#-style extensions.

**Comment by En3Tho** [comment]
I see. Now I understand why you haven't done this yourself already.

Do you see support for C#-style extensions only as a worthy feature?

**Comment by auduchinok** [comment]
> Do you see support for C#-style extensions only as a worthy feature?

Yes, and I think about it from time to time, because adding support for F# extensions is especially challenging for members that come from compiled assemblies. Supporting C#-style extensions only at first would be much simpler indeed. But even it's simpler, I'd suggest not trying to do it yourself, as it'll be more difficult without being able to easily analyse what does C# support do and to compare the various caches implementations. It's one of my personal most wanted features, so I'm going to get there sooner or later. 🙂
