### ISSUE TITLE
To interpolated string should not be offered when referencing old FSharp.Core

### ISSUE THREAD

**Issue by bartelink** [JetBrains/resharper-fsharp#555]
I have some libraries (e.g. FsCodec) that reference FSharp.Core versions e.g. 4.5.4
The 'Format String can be replaced with interpolated string' suggestion is offered.
When you accept, it immediately points out that you need `FSharp.Core` v 6 or later

Ideally for me, I would be able to turn off the suggestion (don't want to update FSharp.Core req; am not aware of whats involved in turning off the suggestion only for this case, and I appreciate it a lot for normal code that is using in-date FSharp.Core)

(I considered logging this about a year ago, but opted not to on the basis that this is super rare and I'd live with it. However it's probably the top niggle I have with Rider that springs to mind!)

If this is difficult to achieve efficiently, I would honestly not like to see much time invested in it and would be more than happy to have the issue closed as wontfix

**Comment by auduchinok** [comment]
@bartelink Could you share a sample project to look at, please?

**Comment by auduchinok** [comment]
@bartelink Thanks for the repro! I've fixed it in https://github.com/JetBrains/resharper-fsharp/commit/9d858b9a6a4f0c2a39496ba5cac421f1a6475ebe.

**Comment by bartelink** [comment]
Neat, thank you for the usual stellar service (and I promise I'll actually pay attention and install the next release!)
