### ISSUE TITLE
Instructions to build the `ReSharper.FSharp` solution are insufficient

### ISSUE THREAD

**Issue by nathanpovo** [JetBrains/resharper-fsharp#565]
The instructions in the README for building the solution are insufficient; it is not possible to build the solution without errors.

https://github.com/JetBrains/resharper-fsharp/blob/4f0754710a9dcfd3bb8e84c1fc0a59353b9e33e9/README.md?plain=1#L39

The MSBuild version is using the dotnet version:

![image](https://github.com/JetBrains/resharper-fsharp/assets/17831160/38263f6c-a2f9-49a8-b223-be2c6fed5dbc)

As soon as I hit "build", I am getting errors throughout the solution (mostly missing namespaces)

![image](https://github.com/JetBrains/resharper-fsharp/assets/17831160/ac0975fa-efc5-496a-9d09-2edbe6a01b93)

![image](https://github.com/JetBrains/resharper-fsharp/assets/17831160/93b981e1-7385-4a70-99dd-1083f967383b)

![image](https://github.com/JetBrains/resharper-fsharp/assets/17831160/06c7747a-2ecd-4494-a5bc-e05088a15178)

Tested with commit https://github.com/JetBrains/resharper-fsharp/commit/4f0754710a9dcfd3bb8e84c1fc0a59353b9e33e9 on the [main branch](https://github.com/JetBrains/resharper-fsharp/tree/main)

**Comment by auduchinok** [comment]
@nathanpovo It looks like the references to R#/Rider SDK are missing. Did `prepare` task from the instructions complete successfully?

We've also had some issues with build due to some internal infrastructure work. I've merged the recent fixes into `main`, could you try it once more, please?

**Comment by nathanpovo** [comment]
> @nathanpovo It looks like the references to R#/Rider SDK are missing. Did `prepare` task from the instructions complete successfully?

What "prepare" task are you refferring to?

I am getting stuck the second step of this section https://github.com/JetBrains/resharper-fsharp/blob/4f0754710a9dcfd3bb8e84c1fc0a59353b9e33e9/README.md#building-the-plugin-and-launching-rider-in-a-sandbox


> We've also had some issues with build due to some internal infrastructure work. I've merged the recent fixes into `main`, could you try it once more, please?

**Comment by auduchinok** [comment]
> What "prepare" task are you refferring to?

The one in the first step of this section https://github.com/JetBrains/resharper-fsharp/blob/4f0754710a9dcfd3bb8e84c1fc0a59353b9e33e9/README.md#building-the-plugin-and-launching-rider-in-a-sandbox.

**Comment by nathanpovo** [comment]
It worked.

I don't know how I completely missed that step 🤦

Apologies for any time wasted.

**Comment by nathanpovo** [comment]
For anyone that stumbles on this ticket, make sure you do not skip this step

![image](https://github.com/JetBrains/resharper-fsharp/assets/17831160/1472165e-6e20-41ee-995f-73251d53a027)
