### ISSUE TITLE
Turn 3560 off by default

### ISSUE THREAD

**Issue by rstm-sf** [JetBrains/resharper-fsharp#588]
Need update FCS? see https://github.com/dotnet/fsharp/pull/16160

![image](https://github.com/JetBrains/resharper-fsharp/assets/2669927/3ccb9abb-ba6c-4da0-bdec-7a7ed351ae5d)

global.json

```json
{
  "sdk": {
    "version": "7.0.202",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

JetBrains Rider 2023.3.2

**Comment by auduchinok** [comment]
> Need update FCS?

Yes, looks like it. Thanks!
