### ISSUE TITLE
Suggesting to highlight the let bound value, ``asyncResult`` to aid auto-importing the ``open FsToolkit.ErrorHandling`` library in the file.

### ISSUE THREAD

**Issue by aguluman** [JetBrains/resharper-fsharp#688]
I have attached 3 images of my experience trying to auto-import ``open FsToolkit.ErrorHandling`` in my projct file,

```Image one```
[image](https://github.com/user-attachments/assets/b63959cd-e07e-433d-8cd8-87a293010cdf)

```image two```
[image](https://github.com/user-attachments/assets/3666f02f-7fa3-4528-9679-81426a14169f)

```image three```
[image](https://github.com/user-attachments/assets/84b45119-6002-4f77-9b14-5d75415fbde4)

I hope these examples help you understand the issue being raised here.

**Comment by auduchinok** [comment]
@aguluman Thank you for writing about it! Could you please share a small repro project, so it would be easier to reproduce the exact scenario that you see?

**Comment by aguluman** [comment]
Hello @auduchinok here a project repo, https://github.com/aguluman/TimeTrackingExercise, I am working on, you can clone and use it. Go to the Features folder in the Accounting and the Rental Project. 

You will see this code in Accounting\Features etc, 
`namespace Accounting.Features

open System
open Accounting
open Accounting.Wallet
open FsToolkit.ErrorHandling

[<RequireQualifiedAccess>]
module CreateWallet =
    type Data = { UserId: UserId }

    let execute (persistWalletEvent: WalletEvent -> Async<unit>) (getInstant: unit -> Instant) walletId (data: Data) =
        asyncResult {
            do!
                persistWalletEvent
                    { WalletEvent.WalletId = walletId
                      UserId = data.UserId
                      EventId = Guid.NewGuid()
                      Data = WalletEventData.Created
                      Instant = getInstant () }
        }
`

I hope it helps you to understand.

**Comment by aguluman** [comment]
This issue has been fixed.

Thank you, whomever fixed it.
