### ISSUE TITLE
Signature/parameter tooltips for F# functions

### ISSUE THREAD

**Issue by slang25** [JetBrains/resharper-fsharp#76]
If we type `Math.Min(<caret>` we see a tooltip with the signatures and overloads for that method as we do in other IDEs.

I would like it so that if I type:
```fsharp
List.fold <caret>
```

We could see the F# signature, and `List.fold` is the perfect example for me as I can never remember the order of parameters,  I would love for the IDE to just tell me what to pass as I move to each parameter, the experience in C# means you can just go into autopilot. I sometimes type `(` just to trigger the type signature, I appreciate that with things like forward piping functions are not as simple as methods.

I looked at this for Ionide and realised triggering completion on every space isn't ideal, and their language service at the time would only let you declare when to run it on a certain character, this would have been an unacceptable overhead for general programing.

I was wondering if this is a sensible suggestion, and if it was feasible in Rider.

**Comment by auduchinok** [comment]
@slang25 Thanks for writing about it! It has been implemented in [Rider 2022.2](https://github.com/JetBrains/resharper-fsharp/blob/net232/RELEASE_NOTES.md#20222).
