### ISSUE TITLE
Open namespace issues

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#85]
Few issues I've come across repeatedly:

1. Rider sometimes adds the open above the first line (above namespace/module), not sure why
2. Rider cannot deal very well with multiple namespaces in the same file, it gets confused where to put the open causing the open to have no effect on the code you're writing.
3. Rider does not take `AutoOpen` into account when it opens from a function suggestion, causing the auto opened module to be added unnecessarily into the completion too.

**Comment by auduchinok** [comment]
There's a related issue at the Rider tracker for it: [RIDER-27924](https://youtrack.jetbrains.com/issue/RIDER-27924).
I'm trying to fix/workaround most of the known problems with symbols import in 2020.1, and `1` and `2` are already fixed in a branch.

**Comment by NinoFloris** [comment]
Ah that's welcome. 

About 3, I guess similarly it should take into account `RequireQualifiedAccess` if it doesn't already.

**Comment by auduchinok** [comment]
Fixes for `1` and `2` are now in: [696ddaf](https://github.com/JetBrains/fsharp-support/commit/696ddafbc1edaf96acf34d2fefc2dd79c9d29b91).

@NinoFloris Could you share some particular repros for the `AutoOpen` and `RequireQualifiedAccess` case you're seeing so I could check it as well?

**Comment by NinoFloris** [comment]
```fs
namespace Foo
[<AutoOpen>]
module Auto = 
    let foo x = ()

namespace Bar
module Bar = 
    let bar x = foo // try to import this, result will be Operators.foo, while foo is enough.  
```

For `RequireQualifiedAccess` I don't have an example but there may be cases where today an import isn't qualified enough for DUs/modules that are annotated with `RequireQualifiedAccess`. It's just somewhat of a dual to `AutoOpen` so it may have similar issues.

I did find another issue related to imports:
4. Importing a non generic symbol living in another namespace as its generic one, say when implementing IEnumerable (IEnumerator<T> IEnumerator) is impossible, this is the same vice versa (opening non generic namespace first). You will see a red symbol but won't get any import suggestions.
5. While exploring 4. I found that import also ignores any generic argument syntax you may have written, and gives you a non generic suggestion as well. I could see that being useful but I'm not sure if there's any ranking that takes the fact you wrote a generic type into account when ordering these suggestions?
<img width="457" alt="Screenshot 2020-02-05 at 16 09 54" src="https://user-images.githubusercontent.com/4218809/73854073-3308c980-4832-11ea-984d-1fb81314eced.png">

**Comment by auduchinok** [comment]
> // try to import this, result will be Operators.foo, while foo is enough.  

Thanks, I see. The text to insert is currently coming from FCS items provider. I'll be looking into it as a part of [RIDER-27924](https://youtrack.jetbrains.com/issue/RIDER-27924) fix.

**Comment by NinoFloris** [comment]
That `Auto` module was meant to be `Operators` of course...

**Comment by NinoFloris** [comment]
Trying to import a nested class (so, defined in C#) causes a compiler error because it just tries to import the parent class, which is not allowed until open static is out of preview.

**Comment by auduchinok** [comment]
@NinoFloris Could you also attach some minimal repro snippets? It's also important to note which import method is used: code completion or a quick fix, since the first one is currently provided by FCS and the second one is done on our side.

**Comment by NinoFloris** [comment]
Working on it :)

**Comment by NinoFloris** [comment]
So quick fix ignores the parent class and imports just the namespace which is wrong in its own way without symbol fixup at the import site, while code completion tries to import the parent class like I said.

it's super simple 

```cs
namespace ReproCs
{
    public class Foo
    {
        public class Bar
        {
        }
    } 
}
```

```fs
module ReproFs

let bar() = Bar // try either quick fix or code completion for the fireworks.
```

**Comment by auduchinok** [comment]
@NinoFloris Yes, this case wasn't implemented yet. Thanks for repro!

**Comment by auduchinok** [comment]
> 5. While exploring 4. I found that import also ignores any generic argument syntax you may have written, and gives you a non generic suggestion as well.

It's also fixed now. If there are any type arguments, the suggested types are filtered based on the type parameters count.

**Comment by auduchinok** [comment]
Nested types qualifiers are also inserted via quick fix now.
Before:
<img width="411" alt="Screenshot 2020-12-14 at 13 04 59" src="https://user-images.githubusercontent.com/3923587/102068105-17d0f800-3e0d-11eb-9a60-f6daf90c94b4.png">
After:
<img width="474" alt="Screenshot 2020-12-14 at 13 05 23" src="https://user-images.githubusercontent.com/3923587/102068112-19022500-3e0d-11eb-8c02-51aa73fb2477.png">

All completion-related issues need separate fixes in FCS and completion side though, but I'm aiming to reusing the logic implemented for the quick fix.

**Comment by auduchinok** [comment]
It seems like all of these issues have been fixed in code completion too.
@NinoFloris If you see other cases, please file a separate issue, and I'll work on it.
